---
title: "STAT 231 PUG Shiny Project"
author: "Ethan Van De Water, Maximo Gonzalez, Alex Nichols"
date: "2023-12-5"
format: pdf
---

```{r include=FALSE}
knitr::opts_chunk$set(eval = TRUE, message = FALSE)

# improve digit and NA display 
options(scipen = 1, knitr.kable.NA = '')

# Load Packages
library(tidyverse)
library(kableExtra)
library(lubridate)
library(ggplot2)
library(readxl)
library(dplyr)
library(rvest)
library(purrr)
library(robotstxt)
library(readxl)
library(plotly)
library(zoo)

```

\newpage
# Data Wrangling


```{r}
oil_pricing_import <- read_excel("data/Oil Pricing.XLSX")

colnames(oil_pricing_import)

oil_wrangled1 <- oil_pricing_import %>%
  select(date, US_pricing, europe_pricing, month, year)

oil_wrangled1$date <- as.yearmon(oil_wrangled1$date, "%b-%Y")

events <- data.frame(
  event_date = as.yearmon(c('Feb-2022', 'Mar-2003'), "%b-%Y"),
  event_label = c('Russia-Ukraine War Start', 'Iraq War Start')
)

# Plot using ggplot
ggplot(oil_wrangled1, aes(x = date)) +
  geom_line(aes(y = US_pricing, color = "US Pricing"), size = 1) +
  geom_line(aes(y = europe_pricing, color = "Europe Pricing"), size = 1) +
  labs(title = "Oil Pricing Over Time", x = "Date", y = "Pricing") +
  scale_color_manual(values = c("US Pricing" = "blue", "Europe Pricing" = "red")) +
  theme_minimal() +
  theme(legend.position = c(0.1, 0.8)) +
  geom_vline(data = events, aes(xintercept = as.numeric(event_date)), linetype = "dashed") +
  annotate("text", x = as.yearmon('Feb-2022', "%b-%Y"), y = Inf, label = "Russia-Ukraine War Start", vjust = 1, hjust = 1.05) +
  annotate("text", x = as.yearmon('Mar-2003', "%b-%Y"), y = Inf, label = "Iraq War Start", vjust = 1, hjust = 1.1) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```


